<?xml version="1.0" encoding="UTF-8"?><action xmlns="http://com.softwareag.rules/action" version="10.0.0.0.85">
    <comment/>
    <type>Process Action</type>
    <implementation>
        <imports/>
        <function>(deffunction actionac1Call (?dataModel ?outputElement ?INPUTIDATA)(bind ?OUTPUTIDATA (defaultServiceCall "wm.monitor.process.actions" "invokeProcessActions" ?INPUTIDATA)) (DataModelHelperUtils.createOutputObjectFromIData ?dataModel ?outputElement ?OUTPUTIDATA (engine)))</function>
        <call>(actionac1Call ?OUTPUT_SIGNATURE (getActionIDataInput ?INPUT_SIGNATURE))</call>
    </implementation>
    <input>
        <datamodel>/RP1/Data Models/Actionac1{sAg}Input.actiondatamodel</datamodel>
        <nsrecord>

&lt;IDataXMLCoder version="1.0"&gt;
  &lt;record javaclass="com.wm.data.ISMemDataImpl"&gt;
    &lt;value name="node_type"&gt;record&lt;/value&gt;
    &lt;value name="is_public"&gt;false&lt;/value&gt;
    &lt;value name="field_name"&gt;ac1&lt;/value&gt;
    &lt;value name="field_type"&gt;record&lt;/value&gt;
    &lt;value name="field_dim"&gt;0&lt;/value&gt;
    &lt;null name="field_opt"/&gt;
    &lt;null name="wrapper_type"/&gt;
    &lt;value name="nillable"&gt;true&lt;/value&gt;
    &lt;null name="field_xmlns"/&gt;
    &lt;value name="form_qualified"&gt;false&lt;/value&gt;
    &lt;value name="is_global"&gt;false&lt;/value&gt;
    &lt;array name="rec_fields" type="record" depth="1"&gt;
      &lt;record javaclass="com.wm.data.ISMemDataImpl"&gt;
        &lt;value name="node_type"&gt;field&lt;/value&gt;
        &lt;record name="node_hints" javaclass="com.wm.util.Values"&gt;
          &lt;value name="field_usereditable"&gt;false&lt;/value&gt;
          &lt;value name="field_largerEditor"&gt;false&lt;/value&gt;
          &lt;value name="field_password"&gt;false&lt;/value&gt;
        &lt;/record&gt;
        &lt;value name="is_public"&gt;false&lt;/value&gt;
        &lt;value name="field_name"&gt;action&lt;/value&gt;
        &lt;value name="field_type"&gt;string&lt;/value&gt;
        &lt;value name="field_dim"&gt;0&lt;/value&gt;
        &lt;null name="field_opt"/&gt;
        &lt;array name="field_options" type="value" depth="1"&gt;
          &lt;value&gt;START&lt;/value&gt;
          &lt;value&gt;JOIN&lt;/value&gt;
          &lt;value&gt;SUSPEND&lt;/value&gt;
          &lt;value&gt;RESUME&lt;/value&gt;
          &lt;value&gt;FAIL&lt;/value&gt;
          &lt;value&gt;CANCEL&lt;/value&gt;
          &lt;value&gt;MANUAL&lt;/value&gt;
        &lt;/array&gt;
        &lt;null name="wrapper_type"/&gt;
        &lt;value name="nillable"&gt;true&lt;/value&gt;
        &lt;null name="field_xmlns"/&gt;
        &lt;value name="form_qualified"&gt;false&lt;/value&gt;
        &lt;value name="is_global"&gt;false&lt;/value&gt;
      &lt;/record&gt;
      &lt;record javaclass="com.wm.data.ISMemDataImpl"&gt;
        &lt;value name="node_type"&gt;record&lt;/value&gt;
        &lt;value name="is_public"&gt;false&lt;/value&gt;
        &lt;value name="field_name"&gt;actionInput&lt;/value&gt;
        &lt;value name="field_type"&gt;recref&lt;/value&gt;
        &lt;value name="field_dim"&gt;0&lt;/value&gt;
        &lt;null name="field_opt"/&gt;
        &lt;null name="wrapper_type"/&gt;
        &lt;value name="nillable"&gt;true&lt;/value&gt;
        &lt;null name="field_xmlns"/&gt;
        &lt;value name="form_qualified"&gt;false&lt;/value&gt;
        &lt;value name="is_global"&gt;false&lt;/value&gt;
        &lt;null name="rec_fields"/&gt;
        &lt;null name="rec_closed"/&gt;
        &lt;null name="schemaRegistered"/&gt;
        &lt;value name="modifiable"&gt;true&lt;/value&gt;
        &lt;null name="schemaCompliant"/&gt;
        &lt;null name="elementWrapper"/&gt;
        &lt;null name="wrappedElement"/&gt;
        &lt;value name="rec_ref"&gt;[RP1]Actionac1{sAg}_actionInputInput&lt;/value&gt;
      &lt;/record&gt;
    &lt;/array&gt;
    &lt;null name="rec_closed"/&gt;
    &lt;null name="schemaRegistered"/&gt;
    &lt;value name="modifiable"&gt;true&lt;/value&gt;
    &lt;null name="schemaCompliant"/&gt;
    &lt;null name="elementWrapper"/&gt;
    &lt;null name="wrappedElement"/&gt;
  &lt;/record&gt;
&lt;/IDataXMLCoder&gt;
</nsrecord>
    </input>
    <inputDefaults>

&lt;IDataXMLCoder version="1.0"&gt;
  &lt;record javaclass="com.wm.data.ISMemDataImpl"&gt;
    &lt;value name="action"&gt;START&lt;/value&gt;
    &lt;record name="actionInput" javaclass="com.wm.data.ISMemDataImpl"&gt;
      &lt;value name="processModelID"&gt;ProcessProject/Process1&lt;/value&gt;
      &lt;value name="doctypeName"&gt;testPackage.docs:doc1&lt;/value&gt;
    &lt;/record&gt;
  &lt;/record&gt;
&lt;/IDataXMLCoder&gt;
</inputDefaults>
    <output>
        <datamodel>/RP1/Data Models/Actionac1{sAg}Output.actiondatamodel</datamodel>
        <nsrecord>

&lt;IDataXMLCoder version="1.0"&gt;
  &lt;record javaclass="com.wm.data.ISMemDataImpl"&gt;
    &lt;value name="node_type"&gt;record&lt;/value&gt;
    &lt;value name="is_public"&gt;false&lt;/value&gt;
    &lt;value name="field_name"&gt;ac1&lt;/value&gt;
    &lt;value name="field_type"&gt;record&lt;/value&gt;
    &lt;value name="field_dim"&gt;0&lt;/value&gt;
    &lt;null name="field_opt"/&gt;
    &lt;null name="wrapper_type"/&gt;
    &lt;value name="nillable"&gt;true&lt;/value&gt;
    &lt;null name="field_xmlns"/&gt;
    &lt;value name="form_qualified"&gt;false&lt;/value&gt;
    &lt;value name="is_global"&gt;false&lt;/value&gt;
    &lt;array name="rec_fields" type="record" depth="1"&gt;
      &lt;record javaclass="com.wm.data.ISMemDataImpl"&gt;
        &lt;value name="node_type"&gt;field&lt;/value&gt;
        &lt;record name="node_hints" javaclass="com.wm.util.Values"&gt;
          &lt;value name="field_largerEditor"&gt;false&lt;/value&gt;
          &lt;value name="field_password"&gt;false&lt;/value&gt;
        &lt;/record&gt;
        &lt;value name="is_public"&gt;false&lt;/value&gt;
        &lt;value name="field_name"&gt;outputMessage&lt;/value&gt;
        &lt;value name="field_type"&gt;string&lt;/value&gt;
        &lt;value name="field_dim"&gt;0&lt;/value&gt;
        &lt;null name="field_opt"/&gt;
        &lt;null name="wrapper_type"/&gt;
        &lt;value name="nillable"&gt;true&lt;/value&gt;
        &lt;null name="field_xmlns"/&gt;
        &lt;value name="form_qualified"&gt;false&lt;/value&gt;
        &lt;value name="is_global"&gt;false&lt;/value&gt;
      &lt;/record&gt;
    &lt;/array&gt;
    &lt;null name="rec_closed"/&gt;
    &lt;null name="schemaRegistered"/&gt;
    &lt;value name="modifiable"&gt;true&lt;/value&gt;
    &lt;null name="schemaCompliant"/&gt;
    &lt;null name="elementWrapper"/&gt;
    &lt;null name="wrappedElement"/&gt;
  &lt;/record&gt;
&lt;/IDataXMLCoder&gt;
</nsrecord>
    </output>
    <return>/outputMessage;1;0</return>
    <dependencies>
        <dependsOn>IS:wm.monitor.process.actions.invokeProcessActions</dependsOn>
        <dependsOn>BPM:ProcessProject_Process1</dependsOn>
    </dependencies>
    <properties>
        <property>
            <propertyName>property.action.name</propertyName>
            <propertyValue>ac1</propertyValue>
        </property>
        <property>
            <propertyName>property.action.call</propertyName>
            <propertyValue>(actionac1Call ?OUTPUT_SIGNATURE (getActionIDataInput ?INPUT_SIGNATURE))</propertyValue>
        </property>
        <property>
            <propertyName>ISServiceName</propertyName>
            <propertyValue>invokeProcessActions</propertyValue>
        </property>
        <property>
            <propertyName>ISServiceNamespace</propertyName>
            <propertyValue>wm.monitor.process.actions</propertyValue>
        </property>
        <property>
            <propertyName>property.action.run.once</propertyName>
            <propertyValue>false</propertyValue>
        </property>
        <property>
            <propertyName>property.action.function</propertyName>
            <propertyValue>(deffunction actionac1Call (?dataModel ?outputElement ?INPUTIDATA)(bind ?OUTPUTIDATA (defaultServiceCall "wm.monitor.process.actions" "invokeProcessActions" ?INPUTIDATA)) (DataModelHelperUtils.createOutputObjectFromIData ?dataModel ?outputElement ?OUTPUTIDATA (engine)))</propertyValue>
        </property>
    </properties>
</action>